site_name: ProLUG Course Books
site_url: http://professionallinuxusersgroup.github.io/course-books
repo_name: ProLUG Course Books
repo_url: https://github.com/ProfessionalLinuxUsersGroup/course-books
edit_uri: edit/main/docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select

nav:
  - Home:
    - index.md
    -  certify.md
    - Contributing to ProLUG MkDocs:
      - contributing.md
      - development.md
  - Linux Admin Course:
    - lac/syllabus.md
    - Unit 1:
      - lac/u1intro.md
      - lac/u1ws.md
      - lac/u1lab.md
      - lac/u1b.md
    - Unit 2:
      - lac/u2intro.md
      - lac/u2ws.md
      - lac/u2lab.md
    - Unit 3:
      - lac/u3intro.md
      - lac/u3ws.md
      - lac/u3lab.md
      - lac/u3b.md
    - Unit 4:
      - lac/u4intro.md
      - lac/u4ws.md
      - lac/u4lab.md
    - Unit 5:
      - lac/u5intro.md
      - lac/u5ws.md
      - lac/u5lab.md
    - Unit 6:
      - lac/u6intro.md
      - lac/u6ws.md
      - lac/u6lab.md
    - Unit 7:
      - lac/u7intro.md
      - lac/u7ws.md
      - lac/u7lab.md
      - lac/u7b.md
    - Unit 8:
      - lac/u8intro.md
      - lac/u8ws.md
      - lac/u8lab.md
      - lac/u8b.md
    - Unit 9:
      - lac/u9intro.md
      - lac/u9ws.md
      - lac/u9lab.md
    - Unit 10:
      - lac/u10intro.md
      - lac/u10ws.md
      - lac/u10lab.md
      - lac/u10b.md
    - Unit 11:
      - lac/u11intro.md
      - lac/u11ws.md
      - lac/u11lab.md
    - Unit 12:
      - lac/u12intro.md
      - lac/u12ws.md
      - lac/u12lab.md
    - Unit 13:
      - lac/u13intro.md
      - lac/u13ws.md
      - lac/u13lab.md
      - lac/u13b.md
    - Unit 14:
      - lac/u14intro.md
      - lac/u14ws.md
      - lac/u14lab.md
    - Unit 15:
      - lac/u15intro.md
      - lac/u15ws.md
      - lac/u15lab.md
    - Unit 16:
      - lac/u16intro.md
      - lac/u16ws.md
      - lac/u16lab.md
  - Linux Security Course:
    - psc/syllabus.md
    - Unit 1:
      - psc/u1intro.md
      - psc/u1ws.md
      - psc/u1lab.md
    - Unit 2:
      - psc/u2intro.md
      - psc/u2ws.md
      - psc/u2lab.md
    - Unit 3:
      - psc/u3intro.md
      - psc/u3ws.md
      - psc/u3lab.md
      - psc/u3b.md
    - Unit 4:
      - psc/u4intro.md
      - psc/u4ws.md
      - psc/u4lab.md
    - Unit 5:
      - psc/u5intro.md
      - psc/u5ws.md
      - psc/u5lab.md
    - Unit 6:
      - psc/u6intro.md
      - psc/u6ws.md
      - psc/u6lab.md
    - Unit 7:
      - psc/u7intro.md
      - psc/u7ws.md
      - psc/u7lab.md
      - psc/u7b.md
    - Unit 8:
      - psc/u8intro.md
      - psc/u8ws.md
      - psc/u8lab.md
      - psc/u8b.md
    - Unit 9:
      - psc/u9intro.md
      - psc/u9ws.md
      - psc/u9lab.md
    - Unit 10:
      - psc/u10intro.md
      - psc/u10ws.md
      - psc/u10lab.md
      - psc/u10b.md

  - Linux Automation Course:
    - pcae/syllabus.md
    - Unit 1:
      - pcae/u1intro.md
      - pcae/u1ws.md
      - pcae/u1lab.md
    - Unit 2:
      - pcae/u2intro.md
      - pcae/u2ws.md
      - pcae/u2lab.md
    - Unit 3:
      - pcae/u3intro.md
      - pcae/u3ws.md
      - pcae/u3lab.md
      - pcae/u3b.md
    - Unit 4:
      - pcae/u4intro.md
      - pcae/u4ws.md
      - pcae/u4lab.md
    - Unit 5:
      - pcae/u5intro.md
      - pcae/u5ws.md
      - pcae/u5lab.md
    - Unit 6:
      - pcae/u6intro.md
      - pcae/u6ws.md
      - pcae/u6lab.md
    - Unit 7:
      - pcae/u7intro.md
      - pcae/u7ws.md
      - pcae/u7lab.md
      - pcae/u7b.md
    - Unit 8:
      - pcae/u8intro.md
      - pcae/u8ws.md
      - pcae/u8lab.md
      - pcae/u8b.md
    - Unit 9:
      - pcae/u9intro.md
      - pcae/u9ws.md
      - pcae/u9lab.md
    - Unit 10:
      - pcae/u10intro.md
      - pcae/u10ws.md
      - pcae/u10lab.md
      - pcae/u10b.md


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/m6VPPD9usw
      name: ProLUG on Discord

    - icon: fontawesome/brands/github
      link: https://github.com/ProfessionalLinuxUsersGroup
      name: ProLUG GitHub Repositories

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@het_tanis8213
      name: Het_Tanis Youtube

    - icon: material/web
      link: https://www.prolug.org/
      name: ProLUG.org

copyright: Copyright &copy; 2025 Professional Linux Users Group

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: ProfessionalLinuxUsersGroup/course-books
  #     branch: main

extra_css:
  - stylesheets/extra.css
