#!/bin/bash
dnf install -y git python3 hostname httpd
git clone https://github.com/AlexProcter/proLUG_coursework/ && cd prolug_coursework
python3 -m venv . && source "$PWD"/bin/activate
pip install -U pip && pip install -U mkdocs mkdocs-material mkdocs-glightbox
# use mkdocs serve -a "$(hostname -I | awk '{print $1}'):8000" for live reloading
mkdocs build -d /var/www/html/ && systemctl enable --now httpd
